INSERT INTO artist (name)
VALUES ('Pink Floyd'),
       ('The Beatles'),
       ('Michael Jackson'),
       ('AC/DC'),
       ('Eagles'),
       ('Led Zeppelin'),
       ('Fleetwood Mac'),
       ('Bruce Springsteen'),
       ('U2'),
       ('Prince'),
       ('Nirvana'),
       ('Guns N\ Roses'),
       ('Queen'),
       ('Carole King'),
       ('Elton John'),
       ('Beach Boys'),
       ('David Bowie'),
       ('Bob Dylan'),
       ('Rolling Stones'),
       ('Jimi Hendrix');