DROP TABLE IF EXISTS genre CASCADE;
CREATE TABLE genre
(
    id   BIGSERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255)
);
INSERT INTO genre(name) VALUES('default');
CREATE SEQUENCE IF NOT EXISTS genre_id_seq START WITH 1 INCREMENT BY 1;